### ISSUE TITLE
Current editor does not handle disposing properly when binded value is set and another editor is initialized

### ISSUE THREAD

**Issue by nguyenhthai** [tinymce/tinymce-blazor#46] opened 2022-05-03 23:25 UTC
Issue: This issue was originally reported in #15. However, the fix to that caused issue with editor toolbar not disposing properly in #43 and thus was removed. 

Reproducible step (Repo [here](https://github.com/nguyenhthai/TinyMceBlazorToolbarIssue)):

- Navigate to Multi-instance Issue page
- A component that contains an instance of editor with value set to "Some text" is rendered initially.
- Select second component using the dropdown.
- The second component with editor seem to be rendered correct. However, console log throws exception:
_**Uncaught (in promise) Error: System.ArgumentException: There is no tracked object with id '#'. Perhaps the DotNetObjectReference instance was already disposed. (Parameter 'dotNetObjectId')**_

**Comment by jscasca** [comment] 2022-05-04 00:21
The initial issue was fixed by removing all events when disposing of the instance which caused toolbar to not be removed when during disposing time.

I will be looking into this and hope to have a PR in soon.

**Comment by nguyenhthai** [comment] 2022-05-04 02:16
I noticed this dispose pattern and feel like we can move the reference dispose after success calling the JS interop method. Not really sure how that will affect the object disposing from Blazor and the JS interop. Or I think a better solution would be to communicate back to Blazor once the JS module have completely destroy the editor and trigger the garbage collector.

https://github.com/tinymce/tinymce-blazor/blob/e712f406aa48c64fc568c1f94e5cff8f8483cca8/TinyMCE.Blazor/Editor.razor#L285-L299

**Comment by jscasca** [comment] 2022-05-09 07:36
I think the main problem was that some events were still bound by the framework, which is what `editor.off()` was trying to fix.

I made #47 to address this

**Comment by nguyenhthai** [comment] 2022-05-09 14:19
> I think the main problem was that some events were still bound by the framework, which is what `editor.off()` was trying to fix.
> 
> I made #47 to address this

I agreed that there could the problem with some events but I still think the reference object should only be disposed after the success of the javascript call. I looked at several articles about blazor interop and most if not all are doing the reference dispose after the js call.

**Comment by jscasca** [comment] 2022-05-11 04:10
Basically, the problem is that the events keep the dotnetref alive, so by getting rid of the bound events we deal with the obj reference. This should happen in the same thread so I don't think there should be a problem. I will try to find an edge case and see if there is any risk. Otherwise, yeah I can wait for the task to complete before disposing of the reference.

**Comment by nguyenhthai** [comment] 2022-05-18 18:00
@jscasca Any update on the bug fix release?

**Comment by jscasca** [comment] 2022-05-20 07:19
@nguyenhthai yes, sorry. The previous code was released earlier today.

We ended up keeping the disposal order in which the dotnet reference is disposed followed by the destroy method call in JS.

This will likely be addressed in the future

**Closed** 2022-07-28 02:09 UTC
Labels: GitHub
